CBIIT/CCDI-Portal-WebPortal

- src/components/Header/CustomizedHeader.js
- src/components/Layout/LayoutView.js
- src/pages/search/searchView.js
> PORTAL-134: Implement: search bar

- src/components/Header/CustomizedHeader.js
> Added search key is empty

- src/bento/landingPageData.js
- src/pages/landing/landingView.js
PORTAL-118: Implement Homepage: Stats bar
> PORTAL-54: Implement CCDI Portal Homepage: Stats bar

- src/pages/landing/landingView.js
Fixed blank part of the Home page, deleted About Section
> Fixed blank part of the Home page, deleted About Section 

- src/bento/landingPageData.js
- src/components/NavBar/CustomizedNavBar.js
- src/pages/landing/landingView.js
Implement - Header and Nav bar
> PORTAL-140: Implement - Header and Nav bar

- src/assets/header/Clear_Icon.svg
- src/components/Header/CustomizedHeader.js
- src/pages/search/searchView.js
PORTAL-140: search box restyling
> PORTAL-140: search box restyling

- src/components/ScrollButton/ScrollButtonView.js
> PORTAL-144: change z-index

- src/components/NavBar/CustomizedNavBar.js
task PORTAL-158: Added home button on navbar
> PORTAL-140: Added home button on navbar

- src/bento/globalFooterData.js
- src/components/Footer/CustomizedFooter.js
> Portal 139: email validation 

- src/components/NavBar/CustomizedNavBar.js
moved about to the right end of the nav bar
> PORTAL-140: move "about" to the right end of nav bar

- src/components/Footer/CustomizedFooter.js
- src/pages/landing/component/carousel2.js
> PORTAL-139: Fix email validation

- public/index.html
- src/components/Footer/CustomizedFooter.js
- src/components/Header/CustomizedHeader.js
- src/pages/landing/component/carousel2.js
Updated Footer color and left vertical border
Updated search box size
Updated title
> PORTAL-139: Update Footer, search box and title

- src/bento/globalFooterData.js
- src/bento/landingPageData.js
- src/components/NavBar/CustomizedNavBar.js
Navbar: shadow darker; replace 'other Applications' with 'other Resources';
Footer: updated footer email;
Home: replace 'other Applications' with 'other Resources';
> PORTAL-54: Homepage, footer and navbar updated

- src/bento/landingPageData.js
- src/pages/landing/component/carousel.js
> PORTAL-54: random number for carousel

- src/bento/landingPageData.js
- src/pages/landing/component/carousel.js
> PORTAL-54: random number for carousel (#44)

- src/pages/landing/component/carousel.js
Fixed the carousel active frame's color and radius
> PORTAL-54: Fixed the carousel active frame's color and radius

- src/pages/landing/component/carousel.js
changed to hover on carousel it will stop rotating
> PORTAL-186: Carousel continue rotation on hover

- src/components/Footer/CustomizedFooter.js
Align the email entry field with the right edge.
> PORTAL-185: Footer Email Entry field Alignment

- src/bento/landingPageData.js
> PORTAL-189: Update dbGaP Capitalization

- src/pages/search/searchView.js
Changed font in search page to Open sans
> Portal 140: Changed font in search page to Open sans

- src/pages/search/components/cards/aboutCard.js
- src/pages/search/components/searchResultSection.js
PORTAL-164: Implement - Search page pagination
> PORTAL-164: Implement - Search page pagination

- src/pages/search/components/cards/aboutCard.js
- src/pages/search/components/searchResultSection.js
* changed highlight style
changed highlight style
* Added Results per Page
Added Results per Page
* Added useRef for useOutsideAlerter for result per page list
Added useRef for useOutsideAlerter for result per page list
* Deleted useless function
Deleted useless function
* changed some css
changed some css
* changed prevIcon and nextIcon
changed prevIcon and nextIcon
* Added Showing part
Added Showing part
* fixed sizeList
fixed sizeList
* Added style to pagination
Added style to pagination
* changed hover css for pagination
changed hover css for pagination
* Added pagelist arrow
Added pagelist arrow
* Added showingContainer
Added showingContainer
* Added margin to number
Added margin
* Changed showing part
Changed showing part
* Added cursor: 'pointer', to pagination
Added cursor: …
> PORTAL-164: Implement - Search page pagination (#67)

- src/pages/landing/landingView.js
Updated hero part Subtitles under headline
> Updated hero part Subtitles under headline (#73)

- src/components/NavBar/CustomizedNavBar.js
Nav Bar - Adjustments to match cancer.gov
> PORTAL-219: Nav Bar - Adjustments to match cancer.gov

- src/pages/news/newsView.js
- src/pages/search/components/searchResultSection.js
> Changed pagination height

- src/pages/news/newsView.js
- src/pages/search/components/searchResultSection.js
* Fix pagination page size popup issue.
* Fix pagination page size issue 2
* Fix pagination page size issue 3
> Fix pagination issue (#93)

- src/pages/about/aboutView.js
- src/pages/error/Error.js
- src/pages/landing/landingView.js
- src/pages/news/newsDetailView.js
- src/pages/news/newsView.js
- src/pages/search/searchView.js
CCDI Hub 508 Color Contrast Review
> PORTAL-141:  CCDI Hub 508 Color Contrast Review

- src/pages/about/aboutView.js
- src/pages/error/Error.js
- src/pages/landing/landingView.js
- src/pages/news/newsDetailView.js
- src/pages/news/newsView.js
- src/pages/search/searchView.js
* Fixed hero part
Fixed hero part
* Change Stats Number new color
Change Stats Number new color
* fixed latestUpdates and application
fixed latestUpdates and application
* Fixed About page
Fixed About page
* Updated 404 page
Updated 404 page
* updated News and and globalsearch
updated News and and globalsearch
* Updated news detail page
Updated news detail page
* Added newsImg header
Added newsImg header
> PORTAL-141:  CCDI Hub 508 Color Contrast Review (#103)

- src/components/NavBar/CustomizedNavBar.js
Changed the behavior of navbar
> PORTAL-269: Empty spaces on Menu bar lead to blank page when clicked

- src/bento/aboutPageData.js
- src/pages/about/aboutView.js
- src/pages/landing/landingView.js
- src/pages/search/components/cards/aboutCard.js
- src/pages/search/searchView.js
task [PORTAL-273]: Updated style on Homepage Hero, Search page and About page
Adjusted home page hero part:
1. Adjusted home page hero part font size and margin
Updated style in Global search page
1. Updated typeable text to be black
2. Increased line spacing between title and description; and line spacing description and url.
3. title color to be darker color
Update style of About page:
1. expand width of text and graphic are to 1080 px on all static pages. Decreased line spacing.
> PORTAL-54: Updated style on Homepage Hero, Search page and About page

- src/bento/newsData.js
task [PORTAL-277]: Update news title for MCI to be 'Molecular Characterization Initiative enrolled more than 1,000 participants '
> PORTAL-165: Updated news Title for MCI

- src/pages/landing/component/carousel.js
- src/pages/search/components/cards/aboutCard.js
- src/pages/search/components/searchResultSection.js
- src/pages/search/components/tabs/searchViewTabs.js
> Remove console and added key

- src/components/Footer/CustomizedFooter.js
- src/components/Header/CustomizedHeader.js
Added blue bold outline to search bar and email register
> PORTAL-279: Add blue bold outline to search bar and email register

- src/bento/newsData.js
Update Slug and Highlight for - MCI, CCDC, CCDI Symposium Remove: Cancer Plan entry.
> PORTAL-284: OCPL News Text Update

- src/bento/newsData.js
* PORTAL-284: OCPL News Text Update
Update Slug and Highlight for - MCI, CCDC, CCDI Symposium Remove: Cancer Plan entry.
* Added . in the CCDC slug
Added . in the CCDC slug
> PORTAL-284: OCPL News Text Update (#125)

- src/bento/landingPageData.js
> PORTAL-209: Updated Homepage Stats

- src/bento/landingPageData.js
> PORTAL-209: Updated Homepage Stats (#127)

- src/pages/landing/landingView.js
'Read More >' links go to that topic on the news main page
> PORTAL-258:  'Read More >' links go to that topic on the news main page

- src/bento/landingPageData.js
"Pediatric Targets" to read "Pediatric Molecular Targets"
> PORTAL-302: "Pediatric Targets" to read "Pediatric Molecular Targets"

- src/pages/search/searchView.js
News Result Listing Header: new color #00838F
> PORTAL-141: News Result Listing Header: new color #00838F

- src/pages/search/searchView.js
News Result Listing Header: new color #00838F
> News Result Listing Header: new color #00838F (#137)

- src/bento/landingPageData.js
Update the external link for MCI to:  https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs002790.v2.p1
> PORTAL-329: Molecular Characterization Initiative (MCI) link Update

- src/bento/landingPageData.js
- src/pages/landing/landingView.js
NCCR
to  'Reported Cases Under Age 40 (1995-2020)'
from 'Entries'
> PORTAL-327: Stats Bar - Text update

- src/pages/news/newsView.js
Maintain white bottom space of 48 px of height. The card can lengthen in order to fit content. Cards should be different lengths.
> PORTAL-237: Design Review - News Main Page Implementation

- src/components/Footer/CustomizedFooter.js
- src/components/Header/CustomizedHeader.js
- src/components/Layout/LayoutView.js
- src/components/NavBar/CustomizedNavBar.js
- src/pages/landing/component/carousel.js
- src/pages/landing/landingView.js
- src/pages/news/newsView.js
Issue: Linked Image missing alternative text (7)
Issue: Missing form label (2)
Issue: Empty Link (3)
Issue: Low contrast
> PORTAL-218: QA 508 Testing & Remediation

- src/pages/landing/landingView.js
1. Stats bar: decrease line spacing slightly for the text below the large numbers. Maintain the spacing between number and first line of text below that.
2. Title: Make Poppins Medium, Title Case,  size 16, line spacing is too big please make smaller; Switched hover and non-hover colors; Increased space between title and body; Changed Background color 
3. Left align CCDI Applications to Explore. Same for Other Resources
4. Explore: made icon larger
> PORTAL-234: Design Review & Update - Initial Home Page Implementation

- src/bento/globalFooterData.js
- src/components/Footer/CustomizedFooter.js
> PORTAL-349: Correct Icon Descriptions

- src/bento/newsData.js
Added back CCDC APRIL newsitem
> PORTAL-317: Added back CCDC APRIL newsitem

- src/pages/landing/landingView.js
> PORTAL-363: Incorrect Icon size under "Explore"

- src/pages/landing/landingView.js
* PORTAL-363: Incorrect Icon size under "Explore"
changed the width
* Changed margin-bottom and added letter-spacing
Changed margin-bottom and added letter-spacing
> PORTAL-363: Incorrect Icon size under "Explore" (#157)

- src/bento/landingPageData.js
> PORTAL-323: Updated stats number (June 2023)

- src/bento/landingPageData.js
> Updated stats number (#159)

- src/pages/landing/component/carousel.js
- src/pages/landing/landingView.js
The home page include includes a pause indicator that can be used to pause the automatic advancement of the carousel On click, the indicator stops the advancement of the carousel.  On second click the carousel re-starts automatic advancement If paused, on page refresh the carousel restarts.
When paused, the up and down carousel navigation arrow still work.  Using the navigation arrows does not restart advancement Keyboard users should be able to navigate to and use the pause indicator.
> PORTAL-347: Design & Implement - Carousel Pause Button

- src/components/ResponsiveFooter/FooterDesktop.js
- src/components/ResponsiveFooter/FooterMobile.js
- src/components/ResponsiveHeader/HeaderDesktop.js
- src/components/ResponsiveHeader/components/NavbarDesktop.js
- src/components/ResponsiveHeader/components/SearchBarDesktop.js
- src/components/ResponsiveHeader/components/SearchBarMobile.js
- src/components/ResponsiveHeader/components/SearchBarTablet.js
> PORTAL-360: Fix small syntax issues

- src/pages/landing/component/carousel.js
Carousel Pause Button changes to START when clicked
> PORTAL-347: Carousel Pause Button changes to START when clicked

- src/components/ResponsiveHeader/components/NavbarDesktop.js
Changed navbar color from green to blue
> Changed navbar color from green to blue

- src/pages/landing/component/carousel.js
Added pause logic into useEffect
> PORTAL-408: "Pause" does not persist on the page change page

- src/bento/landingPageData.js
Cataloged Datasets number changed to 240
> PORTAL-467: Stats at a Glance, Update (Aug 2023)

- src/bento/newsData.js
PORTAL-337: Front End News Update for August Release
> PORTAL-337: Front End News Update for August Release

- src/bento/newsData.js
- Added one new August CCDC Update
- Change the date of 'Molecular Characterization and Clinical Data from Multiple Organizations Released' from MAY 12, 2023 to JULY 20, 2023
> PORTAL-337: Added August CCDC Update

- src/bento/newsData.js
update Img for CCDC July release
> PORTAL-540: update Img for CCDC July release

- src/bento/globalHeaderData.js
- src/bento/landingPageData.js
- src/pages/landing/landingView.js
The CCDI Homepage updated to include the CCDI Inventory under the explore section.
> PORTAL-307: FE part: Add Inventory to Home page Explore

- src/bento/dashTemplate.js
- src/pages/inventory/inventoryStyle.js
Include label of unit of measurement in Age at Diagnosis and Age at Collection filter. Filter should specify age is measured in days.
> PORTAL-640: Facet: Age at Diagnosis and Age at Collection units

- package-lock.json
- package.json
- src/bento/dashTemplate.js
- src/pages/inventory/sideBar/BentoFacetFilterStyle.js
- src/pages/inventory/sideBar/FilterThemeConfig.js
Data element got highlight with the correct section specific color,
Added background highlight for section title.
> PORTAL-633: Faceted data element not highlighted & PORTAL-626: query bar Missing background box

- package-lock.json
- package.json
> PORTAL-625: Bread Crumb Participant ID Label

- src/pages/inventory/sideBar/BentoFacetFilter.js
Replace field placeholder text with 'Participant ID Search'
> PORTAL-646: Participant ID Missing Label

- src/pages/inventory/inventoryStyle.js
> PORTAL-627: Facet Search box no bottom line collapsed

- package-lock.json
- package.json
Remove highlight and leave the background clear/empty. Changed @bento-core/widgets to version 1.0.1-ccdihub.5
> PORTAL-645: Histogram Highlight 508

- src/pages/inventory/tabs/tableConfig/Theme.js
Changed column width to make the layout look better
> PORTAL-632: Files column lengths not balanced

- package-lock.json
- package.json
- src/bento/dashTemplate.js
update package @bento-core/facet-filter": "1.0.1-ccdihub.19
> PORTAL-641: Fix Age at Diagnosis display and spacing.

- package-lock.json
- package.json
- src/pages/inventory/inventoryView.js
> PORTAL-623: missing label on search input

- src/bento/dashTemplate.js
> PORTAL-667: Typo in "AGE AT DIAGNOSIS (DAYS)" filter label

- src/bento/dashboardTabData.js
- src/pages/inventory/tabs/tableConfig/Theme.js
Update the the column labels to read
Diagnosis (Top 5)
Diagnosis Anatomic Site (Top 5)
> PORTAL-629: Studies Tab, Diagnosis & Diagnosis Anatomic Site columns

- src/components/ResponsiveHeader/components/SearchBarDesktop.js
- src/components/ResponsiveHeader/components/SearchBarMobile.js
- src/components/ResponsiveHeader/components/SearchBarTablet.js
> PORTAL-675: 508 Updates: Add label tags

- public/index.html
Ensures that user-scalable="no" is not included in the <meta name="viewport">
> PORTAL-678: 508 Updates: Zooming and scaling must not be disabled

- src/pages/landing/component/latestUpdate.js
> PORTAL-674: 508 Updates: Add Accessible Names to Linked Images

- src/components/ResponsiveFooter/FooterDesktop.js
- src/components/ResponsiveFooter/FooterMobile.js
- src/components/ResponsiveFooter/FooterTablet.js
- src/components/ResponsiveHeader/components/SearchBarDesktop.js
- src/components/ResponsiveHeader/components/SearchBarMobile.js
- src/components/ResponsiveHeader/components/SearchBarTablet.js
> 508 issue: changed search and email id to be unique

- src/pages/inventory/sideBar/BentoFacetFilterStyle.js
> PORTAL-670: Facet, Age at Collection - (Days) overlap

- src/pages/landing/component/latestUpdate.js
> PORTAL-704: Hub Home Page: Rotating Latest Updates cards

- src/bento/globalStatsData.js
- src/components/Stats/StatsView.js
> PORTAL-621: 508, Explore Page - Image Alt Text

- src/bento/fileCentricCartWorkflowData.js
The column name should be "File size" for the Cart.
> PORTAL-734: The column name should be "File size" for the Cart.

- src/bento/dashboardTabData.js
- src/bento/tableDownloadCSV.js
"Diagnosis ID" column should be removed.
> PORTAL-725:"Diagnosis" Tab has the column "Diagnosis ID" which should not be there as per requirement.

- src/bento/dashboardTabData.js
changed order for Studies tab as well as export
> PORTAL-750: Studies Tab, New column order (and export order)

- public/robots.txt
> SEO optimization for CCDI Hub

- src/bento/fileCentricCartWorkflowData.js
> PORTAL-763: CCDI Manifest Export File Typo

- src/pages/inventory/tabs/tableConfig/Theme.js
made 'study_short_title' width as 'file_name'
> PORTAL-654: Results Panel - Adjusting display columns for Studies Tab

- src/bento/globalHeaderData.js
- src/components/ResponsiveHeader/HeaderMobile.js
- src/components/ResponsiveHeader/HeaderTablet.js
- src/pages/about/aboutView.js
- src/pages/landing/component/heroMobile.js
- src/pages/landing/component/latestUpdate.js
- src/pages/landing/landingView.js
changed the feedback on responsive design
> PORTAL-367: Implement - Home Page, Responsive Design

- src/bento/dashTemplate.js
> Changed title to ICD-O DIAGNOSIS

- src/bento/fileCentricCartWorkflowData.js
changed File ID 'file_id' to 'guid'
> PORTAL-768:  Update Manifest File Output

- src/pages/landing/landingView.js
delete small title padding and replace with empty space
> delete small title padding, replace with empty space

- src/components/Header/CustomizedHeader.js
> government shutdown banner

- src/bento/landingPageData.js
Stats at a Glance, Update (Oct. 2023)
> PORTAL-741: Stats at a Glance, Update (Oct. 2023)

- src/components/ResponsiveHeader/components/NavbarDesktop.js
do not display "my file" on destop on navbar
> fixed desktop navbar not to show "my file"

- src/bento/dashboardTabData.js
the <Tab Name> was corrected from Study to Studies
> PORTAL-802: CSV download file name for Studies tab is incorrect

- src/components/ResponsiveHeader/components/NavbarDesktop.js
added tabIndex={0} and onKeyPressHandler
> PORTAL-606: 508 Updates: Fix Tab Order for Applications and Other Resources Navigation

- src/components/ResponsiveHeader/components/NavbarDesktop.js
Fixed tab issue
deleted my file from desktop navbar
> Fixed tab issue and deleted my file from desktop navbar

- src/components/ResponsiveHeader/components/LogoDesktop.js
- src/components/ResponsiveHeader/components/LogoMobile.js
- src/components/ResponsiveHeader/components/LogoTablet.js
> PORTAL-737: 508 Compliance: empty links

- src/bento/newsData.js
- src/pages/news/newsView.js
Implement Mobile/Responsive News Main Page
> PORTAL-514: Implement - Mobile/Responsive News Main Page

- src/components/ResponsiveHeader/components/LogoDesktop.js
- src/components/ResponsiveHeader/components/LogoMobile.js
- src/components/ResponsiveHeader/components/LogoTablet.js
- src/pages/inventory/inventoryStyle.js
- src/pages/inventory/inventoryView.js
- src/pages/inventory/tabs/wrapperConfig/Wrapper.js
change link to NavLink, also fixed the logo
> PORTAL-820: Facet selections not retained when navigating back from the cart w/ Explore link

- Dockerfile
package updates to resolve CVE's
> Update Dockerfile to resolve vulnerability

- src/pages/inventory/tabs/tableConfig/Column.js
updated the ellipse to Read More and Read Less
> PORTAL-764: update the ellipse to Read More

- src/bento/dashboardTabData.js
added study_id. also changed the order mentioned in PORTAL-805: Order of columns in the results table - Participants tab does not match with the requirement.
> PORTAL-852: Column Header Update - Order & Name

- public/index.html
- src/pages/about/aboutView.js
Added Gov Banner for Inventory 2.0.0
> Ruoxi pr for Inventory 2.0.0 Gov Banner

- src/bento/landingPageData.js
- src/components/Layout/LayoutView.js
- src/pages/landing/landingController.js
- src/pages/landing/landingView.js
get the number of MCI from api
> PORTAL-853: API Driven MCI Counts

- src/pages/landing/landingView.js
- src/pages/resource/MCIResourceView.js
1. remove icon from MCI
2. scroll back to top on MCI page
3. changed to Navlink
> PORTAL-865: remove icon from MCI and scroll back to top on MCI page

- src/bento/mciData.js
- src/pages/resource/MCIResourceView.js
The wordings for "Assay" under Clinical Molecular Characterization Initiative Assays and Analytics is not correct. The Abbreviations are missing too
> PORTAL-947: The wordings for "Assay" under Clinical Molecular Characterization Initiative Assays and Analytics is not correct

- src/pages/resource/MCIResourceView.js
Added title Introduction on MCI page
> Added title Introduction on MCI page

- package.json
Updated bento package: @bento-core/query-bar: 1.0.1-ccdihub.8
> PORTAL-806: Visually link Facet and Breadcrumb with matching colors

- package.json
Updated @bento-core/widgets: 1.0.1-ccdihub.6
> PORTAL-845: Histogram - Update Tool tip (Participants)

- src/bento/landingPageData.js
- src/pages/landing/component/carousel.js
> PORTAL-962: Updated MCI Carousel Link

- src/bento/landingPageData.js
- src/pages/landing/landingController.js
> PORTAL-354: API Driven CCDC Cataloged Datasets Counts

- package.json
- src/pages/inventory/tabs/wrapperConfig/Theme.js
- src/pages/inventory/tabs/wrapperConfig/Wrapper.js
Description:  
Add a disclaimer to the bottom left margin of the results table 
Updated Bento Packages:  
@bento-core/paginated-table@1.0.1-ccdihub.78
> PORTAL-972: Explore Dashboard Data Disclaimer

- src/bento/mciData.js
Updated the Title to: Enrollment in MCI (APEC14B1-MCI) by Diagnosis Type
> PORTAL-1013: Updated donut chart Title

- src/pages/resource/components/MCINumberTable.js
expand the number of rows on table from 6 to 12
> PORTAL-984: expand the number of rows on table from 6 to 12

- src/pages/error/Error.js
Reverts CBIIT/CCDI-Portal-WebPortal#304
> Revert "peer review test commit"

- src/bento/globalHeaderData.js
- src/components/ResponsiveHeader/HeaderMobile.js
- src/components/ResponsiveHeader/HeaderTablet.js
- src/components/ResponsiveHeader/components/NavbarDesktop.js
Menu bar links updated to direct to the resources themselves, instead of the home page links.
> PORTAL-1064

- src/components/common/mapGenerator.js
> PORTAL-1091

- public/index.html
Updated Adobe Analytics script
> PORTAL-1106: Update Adobe Analytics script

- src/bento/newsData.js
Updated news Application Updates
> PORTAL-1157: CCDI Hub News section : The news updates are updated under "All" type instead of "Application Updates"

- src/bento/newsData.js
> PORTAL-1028: March (2024) News Feed Update

- src/bento/dashTemplate.js
- src/bento/dashboardTabData.js
- src/bento/tableDownloadCSV.js
This reverts commit 14318286b3140d3ddc18dd7d9aa54ef4954ee596.
> Revert "PORTAL-1347: Depreciate ethnicity (#401)"

- src/bento/dashboardTabData.js
- src/bento/tableDownloadCSV.js
- Remove Diagnosis properties in Sample table (except Diagnosis System Classification)
- Add Sample ID to Diagnosis Tabel
> PORTAL-1372: Remove diagnosis properties in Sample nodes

- src/bento/dashTemplate.js
- src/bento/dashboardTabData.js
- src/bento/tableDownloadCSV.js
- Comment out tumor_grade_source and tumor_stage_source code
- Format Last Known Survival Status column values
> PORTAL-1351: Update diagnosis table

- src/bento/cpiResourceData.js
> PORTAL-1622: Remove ellipses on CPI page

- src/pages/about/publications/publicationsController.js
- src/pages/about/publications/publicationsView.js
Added bannerText for publication page
> PORTAL-2047: Update publications on CCDI-Supported Publications Page- April 2025
